// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddRecordRequest add record request
//
// swagger:model AddRecordRequest
type AddRecordRequest struct {

	// dialog id
	DialogID string `json:"dialog_id,omitempty"`

	// record
	Record interface{} `json:"record,omitempty"`
}

// Validate validates this add record request
func (m *AddRecordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add record request based on context it is used
func (m *AddRecordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddRecordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddRecordRequest) UnmarshalBinary(b []byte) error {
	var res AddRecordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
