// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddRecordResponse add record response
//
// swagger:model AddRecordResponse
type AddRecordResponse struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this add record response
func (m *AddRecordResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add record response based on context it is used
func (m *AddRecordResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddRecordResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddRecordResponse) UnmarshalBinary(b []byte) error {
	var res AddRecordResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
