// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddDialogResponse add dialog response
//
// swagger:model AddDialogResponse
type AddDialogResponse struct {

	// dialog id
	DialogID string `json:"dialog_id,omitempty"`
}

// Validate validates this add dialog response
func (m *AddDialogResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this add dialog response based on context it is used
func (m *AddDialogResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddDialogResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddDialogResponse) UnmarshalBinary(b []byte) error {
	var res AddDialogResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
