// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRecordRequest update record request
//
// swagger:model UpdateRecordRequest
type UpdateRecordRequest struct {

	// record
	Record interface{} `json:"record,omitempty"`

	// record id
	RecordID string `json:"record_id,omitempty"`
}

// Validate validates this update record request
func (m *UpdateRecordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update record request based on context it is used
func (m *UpdateRecordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRecordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRecordRequest) UnmarshalBinary(b []byte) error {
	var res UpdateRecordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
